### ISSUE TITLE
Refactor complet

### ISSUE THREAD

**Issue by Batalex** [LaBaleineFr/LaBaleineDeWallStreet#4]
# Proposition
Je propose un refactor complet du bot, car en l'état non maintenable et vraiment pas flatteur.
Un découpage (modules/classes/etc.) par fonctionnalité serait appréciable.

# Tasks
- [x] :shirt:  recommandations des PEP8
- [x] :hammer: découpage par feature
- [x] :bulb: commenter/documenter le code
- [x] :rotating_light: (meilleure) gestion des exceptions
- [x]  :zap: autres améliorations ?

**Comment by spectras** [comment]
Refactor fait en bonne partie. Pour la suite, je propose d'ouvrir un ticket par feature afin de permettre un suivi individuel.
